import './globals.css'
import { Ubuntu } from 'next/font/google';

export const metadata = {
  title: 'Frontend Mentor - Multi Step Form',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main>
          <header className='header'>
            <span className='header__list-item header__list-item--active'>1</span>
            <span className='header__list-item header__list-item--inactive '>2</span>
            <span className='header__list-item header__list-item--inactive'>3</span>
            <span className='header__list-item header__list-item--inactive'>4</span>
          </header>
          {children}
        </main>
        <footer className='footer'>
          <a href='#' className='btn btn--primary'>Next Step</a>
        </footer>
      </body>
    </html>
  )
}
